spring.data.mongodb:
  uri: mongodb+srv://immiportalroot:qmHr8vPd29rz4e8m@immiportalcluster-hebmd.mongodb.net/immiportal?retryWrites=true&w=majority
  database: immiportal

okta:
  oauth2:
    issuer: https://dev-565937.okta.com/oauth2/default